# Generated by Django 5.2.7 on 2025-10-13 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Komisyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Komisyon Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Komisyon',
                'verbose_name_plural': 'Komisyonlar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('YETKILI', 'Yetkili'), ('BIRIM_BASKANI', 'Birim Başkanı'), ('UYE', 'Standart Üye')], default='UYE', max_length=20, verbose_name='Kullanıcı Rolü')),
                ('statü', models.CharField(choices=[('BEKLEMEDE', 'Onay Bekliyor'), ('AKTIF', 'Aktif'), ('REDDEDILDI', 'Reddedildi')], default='BEKLEMEDE', max_length=20, verbose_name='Hesap Statüsü')),
                ('komisyonlar', models.ManyToManyField(blank=True, to='uyeler.komisyon', verbose_name='Ait Olduğu Komisyonlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profiller',
            },
        ),
    ]
