# Generated by Django 5.2.7 on 2025-10-13 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uyeler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='ozel_notlar',
            field=models.TextField(blank=True, null=True, verbose_name='Özel Not Defteri'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='rol',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Yetkili / İlçe Başkanı'), ('BIRIM_BASKANI', 'Yönetici / Birim Başkanı'), ('UYE', 'Standart Üye')], default='UYE', max_length=20, verbose_name='Kullanıcı Rolü'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
