# Generated by Django 5.2.7 on 2025-10-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uyeler", "0002_profil_ozel_notlar_alter_profil_rol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profil",
            name="ozel_notlar",
            field=models.TextField(blank=True, null=True, verbose_name="Özel Notlar"),
        ),
        migrations.AlterField(
            model_name="profil",
            name="rol",
            field=models.CharField(
                choices=[
                    ("YETKILI", "Yetkili"),
                    ("BIRIM_BASKANI", "Birim Başkanı"),
                    ("UYE", "Standart Üye"),
                ],
                default="UYE",
                max_length=20,
                verbose_name="Kullanıcı Rolü",
            ),
        ),
    ]
