# Generated by Django 5.2.7 on 2025-10-14 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uyeler", "0003_alter_profil_ozel_notlar_alter_profil_rol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Duyuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Duyuru Başlığı"),
                ),
                ("icerik", models.TextField(verbose_name="Duyuru İçeriği")),
                (
                    "yayin_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yayın Tarihi"
                    ),
                ),
                (
                    "yazar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yazarı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Duyuru",
                "verbose_name_plural": "Duyurular",
                "ordering": ["-yayin_tarihi"],
            },
        ),
    ]
