# Generated by Django 5.2.7 on 2025-10-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uyeler", "0004_duyuru"),
    ]

    operations = [
        migrations.CreateModel(
            name="Galeri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Resim Başlığı"),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "resim",
                    models.ImageField(
                        upload_to="galeri/", verbose_name="Resim Dosyası"
                    ),
                ),
                ("yuklenme_tarihi", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Galeri Resmi",
                "verbose_name_plural": "Galeri Resimleri",
                "ordering": ["-yuklenme_tarihi"],
            },
        ),
    ]
