# Generated by Django 5.2.7 on 2025-10-14 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uyeler", "0005_galeri"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Etkinlik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("SABAH_NAMAZI", "Sabah Namazı"),
                            ("HALI_SAHA", "Halı Saha"),
                            ("PIKNIK", "Piknik"),
                            ("KAMP", "Kamp"),
                            ("DIGER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Etkinlik Tipi",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Etkinlik Başlığı"),
                ),
                (
                    "mekan",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Mekan (Cami, Halı Saha Adı vb.)",
                    ),
                ),
                ("tarih_saat", models.DateTimeField(verbose_name="Tarih ve Saat")),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "olusturan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etkinlik",
                "verbose_name_plural": "Etkinlikler",
                "ordering": ["-tarih_saat"],
            },
        ),
    ]
