# Generated by Django 5.2.7 on 2025-10-15 16:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uyeler", "0006_etkinlik"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Albüm Başlığı"),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Albüm Tarihi (Değiştirilebilir)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Albüm",
                "verbose_name_plural": "Albümler",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="Fotograf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resim",
                    models.ImageField(
                        upload_to="galeri/", verbose_name="Resim Dosyası"
                    ),
                ),
                (
                    "yuklenme_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yüklenme Tarihi"
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotograflar",
                        to="uyeler.album",
                        verbose_name="Ait Olduğu Albüm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotoğraf",
                "verbose_name_plural": "Fotoğraflar",
                "ordering": ["yuklenme_tarihi"],
            },
        ),
        migrations.DeleteModel(
            name="Galeri",
        ),
    ]
