# Generated by Django 5.2.7 on 2025-10-15 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uyeler", "0007_album_fotograf_delete_galeri"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fotograf",
            options={
                "ordering": ["-yuklenme_tarihi"],
                "verbose_name": "Fotoğraf",
                "verbose_name_plural": "Fotoğraflar",
            },
        ),
        migrations.AlterModelOptions(
            name="profil",
            options={},
        ),
        migrations.RemoveField(
            model_name="etkinlik",
            name="olusturma_tarihi",
        ),
        migrations.AddField(
            model_name="album",
            name="olusturan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="olusturma_tarihi",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="duyuru",
            name="baslik",
            field=models.CharField(max_length=200, verbose_name="Başlık"),
        ),
        migrations.AlterField(
            model_name="duyuru",
            name="icerik",
            field=models.TextField(verbose_name="İçerik"),
        ),
        migrations.AlterField(
            model_name="duyuru",
            name="yazar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Yazarı",
            ),
        ),
        migrations.AlterField(
            model_name="etkinlik",
            name="aciklama",
            field=models.TextField(default="", verbose_name="Açıklama"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="etkinlik",
            name="mekan",
            field=models.CharField(default="", max_length=255, verbose_name="Mekan"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="etkinlik",
            name="olusturan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan",
            ),
        ),
        migrations.AlterField(
            model_name="etkinlik",
            name="tip",
            field=models.CharField(
                choices=[
                    ("SOHBET", "Sohbet"),
                    ("KONFERANS", "Konferans"),
                    ("GEZI", "Gezi"),
                    ("SABAH_NAMAZI", "Sabah Namazı"),
                    ("DIGER", "Diğer"),
                ],
                max_length=20,
                verbose_name="Etkinlik Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="profil",
            name="komisyonlar",
            field=models.ManyToManyField(
                blank=True,
                to="uyeler.komisyon",
                verbose_name="İlgili Olduğu Komisyonlar",
            ),
        ),
        migrations.AlterField(
            model_name="profil",
            name="ozel_notlar",
            field=models.TextField(
                blank=True, null=True, verbose_name="Yönetici Notları"
            ),
        ),
        migrations.AlterField(
            model_name="profil",
            name="statü",
            field=models.CharField(
                choices=[
                    ("BEKLEMEDE", "Onay Bekliyor"),
                    ("AKTIF", "Aktif"),
                    ("REDDEDILDI", "Reddedildi"),
                ],
                default="BEKLEMEDE",
                max_length=20,
                verbose_name="Hesap Durumu",
            ),
        ),
    ]
