# Generated by Django 5.2.7 on 2025-10-17 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uyeler", "0008_alter_fotograf_options_alter_profil_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Not",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=255, verbose_name="Not Başlığı"),
                ),
                (
                    "icerik",
                    models.TextField(blank=True, null=True, verbose_name="Not İçeriği"),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme"),
                ),
                (
                    "onemli_mi",
                    models.BooleanField(
                        default=False, verbose_name="Önemli Olarak İşaretle"
                    ),
                ),
                (
                    "renk",
                    models.CharField(
                        choices=[
                            ("GRI", "Varsayılan"),
                            ("SARI", "Hatırlatıcı"),
                            ("KIRMIZI", "Acil"),
                            ("MAVI", "Fikir"),
                            ("YESIL", "Görev"),
                        ],
                        default="GRI",
                        max_length=10,
                        verbose_name="Not Rengi",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notlar",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Notun Sahibi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kişisel Not",
                "verbose_name_plural": "Kişisel Notlar",
                "ordering": ["-onemli_mi", "-guncelleme_tarihi"],
            },
        ),
    ]
