# Generated by Django 5.2.7 on 2025-10-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uyeler", "0009_not"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad Soyad")),
                (
                    "contact_info",
                    models.CharField(
                        max_length=255, verbose_name="E-posta veya Telefon Numarası"
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Konu")),
                ("message", models.TextField(verbose_name="Mesajınız")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Gönderim Zamanı"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Okundu mu?"),
                ),
            ],
            options={
                "verbose_name": "İletişim Mesajı",
                "verbose_name_plural": "İletişim Mesajları",
                "ordering": ["-timestamp"],
            },
        ),
    ]
