# Generated by Django X.X.X on YYYY-MM-DD HH:MM
import os
from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()
    
    # Render'daki Environment Variables'dan bilgileri alacağız
    DJANGO_SUPERUSER_USERNAME = os.environ.get('DJANGO_SUPERUSER_USERNAME')
    DJANGO_SUPERUSER_EMAIL = os.environ.get('DJANGO_SUPERUSER_EMAIL')
    DJANGO_SUPERUSER_PASSWORD = os.environ.get('DJANGO_SUPERUSER_PASSWORD')

    # Eğer bu değişkenler tanımlı değilse veya kullanıcı zaten varsa, hiçbir şey yapma
    if not all([DJANGO_SUPERUSER_USERNAME, DJANGO_SUPERUSER_PASSWORD]):
        print("Superuser environment variables not set. Skipping.")
        return

    if User.objects.filter(username=DJANGO_SUPERUSER_USERNAME).exists():
        print(f"Superuser '{DJANGO_SUPERUSER_USERNAME}' already exists. Skipping.")
        return

    # Superuser'ı oluştur
    print(f"Creating superuser '{DJANGO_SUPERUSER_USERNAME}'...")
    User.objects.create_superuser(
        username=DJANGO_SUPERUSER_USERNAME,
        email=DJANGO_SUPERUSER_EMAIL,
        password=DJANGO_SUPERUSER_PASSWORD
    )
    print("Superuser created successfully.")


class Migration(migrations.Migration):

    dependencies = [
        ('uyeler', '0001_initial'), # Buradaki '0001_initial' kısmının doğru olduğundan emin ol
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]