# Generated by Django 5.2.7 on 2025-10-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uyeler", "0010_contactmessage"),
        ("uyeler", "0011_create_superuser"),
    ]

    operations = []
